development:
  adapter: postgresql
  database: development
  username: postgres #change it depending on your env
  password: p@ssw0rd #change it depending on your env
  host: localhost
  encoding: utf-8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production
  username: postgres
  password:
  host:
  encoding: utf-8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test
  username: postgres
  password: p@ssw0rd
  host: localhost
  encoding: utf-8
  pool: 5
  timeout: 5000
